// The distribution banner (name/version/license) is generated by
// scripts/build.mjs from package.json.

import { PatapataTextElement } from './elements/text.ts';
import { PatapataClockElement } from './elements/clock.ts';
import { PatapataTimerElement } from './elements/timer.ts';
import { PatapataControlElement } from './elements/control.ts';

if (!customElements.get('patapata-text')) {
  customElements.define('patapata-text', PatapataTextElement);
}

if (!customElements.get('patapata-clock')) {
  customElements.define('patapata-clock', PatapataClockElement);
}

if (!customElements.get('patapata-timer')) {
  customElements.define('patapata-timer', PatapataTimerElement);
}

if (!customElements.get('patapata-control')) {
  customElements.define('patapata-control', PatapataControlElement);
}
